name: dart_client
version: 0.0.1
description: >-
  Calling C code from Dart with FFI

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  ffigen: ^7.2.9

ffigen:
  name: Calculations
  output: './lib/bindings.dart'
  headers:
    entry-points:
      - './lib/calculations.hpp'

