/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculationsJNI */

#ifndef _Included_CalculationsJNI
#define _Included_CalculationsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculationsJNI
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_CalculationsJNI_add
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
