/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculationsJNI */

#ifndef _Included_CalculationsJNI
#define _Included_CalculationsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculationsJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_CalculationsJNI_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
